---
downloads: ~/.ansible-downloads/

configure_zsh: true
oh_my_zsh_theme: robbyrussell
oh_my_zsh_plugins:
  - git
  - brew
  - history
  - kubectl
  - docker
  - docker-compose
oh_my_zsh_install: yes

configure_dotfiles: true
configure_terminal: false
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: 
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/wbrydak/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - coreutils
  - fzf
  - git
  - github/gh/gh
  - go
  - node
  - numpy
  - pinentry-mac
  - pure
  - readline
  - openssl
  - pv
  - terraform
  - wget
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - hashicorp/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - affinity-designer
  - clockify
  - google-chrome
  - notion
  - spotify
  - zoom
  - android-platform-tools
  - dash
  - iterm2
  - obs
  - telegram
  - bitwarden
  - docker
  - lastpass
  - rectangle
  - clickup
  - messenger
  - slack
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
